[package]
name = "mcleaner"
version = "0.1.0"
description = "A cross-platform package manager and cleaner"
authors = ["AndreyMur"]
license = "MIT"
repository = "https://github.com/AndreyMur/MCleaner"
homepage = "https://github.com/AndreyMur/MCleaner"
edition = "2021"
default-run = "mcleaner"

[lib]
name = "mcleaner_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.32"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
